# The public url
GET http://localhost:5000

###

# Get all users
GET http://localhost:5000/api/users

###

# Create a new user
POST http://localhost:5000/api/users
Content-Type: application/x-www-form-urlencoded

username=edlavio

###

# Create a new exercise
POST http://localhost:5000/api/users/66df846f9736b48be7d947c0/exercises
Content-Type: application/x-www-form-urlencoded

description=Teste&duration=20&date=2024-05-09

###

# Get user logs
GET http://localhost:5000/api/users/66df846f9736b48be7d947c0/logs?from=2024-05-05&to=2024-05-10&limit=10